# Better prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# More intuitive splits
bind s split-window -h
bind v split-window -v

# vim keys for pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
